name: DCPS-NLP
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - numpy=1.26.4
  - pandas=2.2.2
  - langchain=0.1.20
  - langchain-core=0.1.52
  - langchain-community=0.0.38
  - llama-cpp-python=0.2.24
  - openai=1.34.0
  - pip:
    - python-dotenv==1.0.1